// <auto-generated />
namespace Proyecto2_2024a.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NombreDeTuMigracion1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NombreDeTuMigracion1));
        
        string IMigrationMetadata.Id
        {
            get { return "202408050219474_NombreDeTuMigracion1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
